name: CI - Calculadora Extendida

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests
      run: |
        export PYTHONPATH=${{ github.workspace }}
        pytest tests/ -v

    - name: Coverage Report
      run: |
        export PYTHONPATH=${{ github.workspace }}
        pytest --cov=app --cov-report=term --cov-report=html

    - name: Save coverage artifact
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: htmlcov/
