name: Docker en Self-hosted

on:
  push:
    branches: [dia18]

jobs:
  docker-build:
    runs-on: [self-hosted]

    steps:
    - uses: actions/checkout@v4

    - name: Build Docker
      run: docker build -t mi-calculadora:runner .

    - name: Test Docker
      run: |
        docker run -d --name calculadora-runner -p 5000:5000 mi-calculadora:runner
        sleep 10
        curl -f http://localhost:5000/health
        docker stop calculadora-runner && docker rm calculadora-runner
